project_id = "cvrpucnzpzzbmckphtks"

[functions.hello-world]
verify_jwt = false

[functions.lionel-coach]
verify_jwt = true

[functions.generate-subtitles]
verify_jwt = true

[functions.lionel-reflection-feedback]
verify_jwt = true
